train:
  batch_size: 32
  num_workers: 10
  lr: 0.001
  resume: False
  self_train: True
  optim_step: [15, 25, 31]
log_path: ./log

dataset:
  train_path: LC2WF_data/train.txt
  test_path: LC2WF_data/test.txt
  use_real: False
  if_cat: False
  sample_number: 512

  LineCloud_path: LC2WF_data/LineCloud_0130_P123
  PredJunc_path: ./log/outputPredJunc


seed: 1555

mode: "eval"

write_pred_wireframe: True
output_path: ./log/outputPredWireframe


model:
  load_model: './pretrained/edge.pth'

Net:
  input_dim: 6
transformer:
  hidden_dim: 256
  dropout: 0.5
  nheads: 8
  dim_feedforward: 256
  num_encoder_layers: 1
  num_decoder_layers: 2
  num_queries: 50
  pre_norm: True